### ISSUE TITLE
Missing indicators in result comparation

### ISSUE THREAD

**Issue by DA21S321D** [usail-hkust/LLMTSCS#13]
![图片](https://github.com/usail-hkust/LLMTSCS/assets/56549016/9a30dbcb-74f9-40fe-bc07-cb6674d5351f)
As the results shown in the picture, the upper side is gpt-3.5-turbo which have run with `--prompt Commonsense ` and the lower side is `Advanced-MPLight`. The` test_avg_queue_len` `test_avg_travel_time` `test_avg_waiting_time` is missing compared to Advanced-MPLight. Is that beacuse i am using `--prompt Commonsense` rather than `--prompt Wait Time Forecast` ?

**Comment by Gungnir2099** [comment]
We don't collect data on `test_avg_queue_len`, `test_avg_travel_time`, or `test_avg_waiting_time` for GPT models. The GPT version we employed is gpt-3.5-turbo-0613, which demonstrates significantly suboptimal performance. Since our publication, there have been multiple updates to the model. But it's a great sign GPT-3.5 works now.

**Comment by DA21S321D** [comment]
Thanks for your explanation :)

**Comment by DA21S321D** [comment]
By the way, what's different between` test_avg_queue_len` and `test_avg_queue_len_over`?

**Comment by Gungnir2099** [comment]
`test_avg_queue_len` is the test result after each training epoch, while we only use GPT models for inference without training. So we do not record `test_avg_queue_len`.
